project:
  type: book
  output-dir: docs

lang: es
language:
  title-block-author-single: "Autor"

book:
  title: "Desarrollo e implementación con tecnologías libres de un dispositivo portátil para evaluar el confort térmico, lumínico y acústico en interiores"
  output-file: "Tesis-JRHA"
  author: 
    name: "José Ramón Hernández Aguilar"
    email: hdezagjr@gmail.com
  date: "05/05/2025"
  chapters:
    - index.qmd
    - capitulo_1.qmd
    - capitulo_2.qmd
    - capitulo_3.qmd
    - capitulo_4.qmd
    - capitulo_5.qmd
    - referencias.qmd

  navbar:
    title: false
    search: true

  sidebar:
    style: floating
    search: true
    collapse-level: 1

comments:
  hypothesis: true

format:
  html:
    toc: true
    toc-title: Contenido
    toc-depth: 4
    number-depth: 3
    theme:
      light: cosmo
    smooth-scroll: true
    code-link: true
  # latex:
  #   documentclass: scrbook

bibliography: references.bib